MODEL_PARAMS = \
{ 'aggregationInfo': { 'days': 0,
                       'fields': [],
                       'hours': 0,
                       'microseconds': 0,
                       'milliseconds': 0,
                       'minutes': 0,
                       'months': 0,
                       'seconds': 0,
                       'weeks': 0,
                       'years': 0},
  'model': 'CLA',
  'modelParams': { 'anomalyParams': { u'anomalyCacheRecords': None,
                                      u'autoDetectThreshold': None,
                                      u'autoDetectWaitRecords': None},
                   'clParams': { 'alpha': 0.00628955245232779,
                                 'clVerbosity': 0,
                                 'regionName': 'CLAClassifierRegion',
                                 'steps': '1'},
                   'inferenceType': 'TemporalMultiStep',
                   'sensorParams': { 'encoders': { '_classifierInput': { 'classifierOnly': True,
                                                                         'clipInput': True,
                                                                         'fieldname': 'theta_dot',
                                                                         'maxval': 10,
                                                                         'minval': -10,
                                                                         'n': 80,
                                                                         'name': '_classifierInput',
                                                                         'type': 'ScalarEncoder',
                                                                         'w': 21},
                                                   u'theta': { 'clipInput': True,
                                                               'fieldname': 'theta',
                                                               'maxval': 3.14159265359,
                                                               'minval': -3.14159265359,
                                                               'n': 191,
                                                               'name': 'theta',
                                                               'type': 'ScalarEncoder',
                                                               'w': 21},
                                                   u'theta_dot': { 'clipInput': True,
                                                                   'fieldname': 'theta_dot',
                                                                   'maxval': 10,
                                                                   'minval': -10,
                                                                   'n': 54,
                                                                   'name': 'theta_dot',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'x': { 'clipInput': True,
                                                                   'fieldname': 'x',
                                                                   'maxval': 10,
                                                                   'minval': -10,
                                                                   'n': 54,
                                                                   'name': 'x',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'x_dot': { 'clipInput': True,
                                                                   'fieldname': 'x_dot',
                                                                   'maxval': 10,
                                                                   'minval': -10,
                                                                   'n': 54,
                                                                   'name': 'x_dot',
                                                                   'type': 'ScalarEncoder',
                                                                   'w': 21},
                                                   u'u': None},
                                     'sensorAutoReset': None,
                                     'verbosity': 0},
                   'spEnable': True,
                   'spParams': { 'columnCount': 2048,
                                 'globalInhibition': 1,
                                 'inputWidth': 0,
                                 'maxBoost': 2.0,
                                 'numActiveColumnsPerInhArea': 40,
                                 'potentialPct': 0.8,
                                 'seed': 1956,
                                 'spVerbosity': 0,
                                 'spatialImp': 'cpp',
                                 'synPermActiveInc': 0.05,
                                 'synPermConnected': 0.1,
                                 'synPermInactiveDec': 0.07204884241766615},
                   'tpEnable': True,
                   'tpParams': { 'activationThreshold': 12,
                                 'cellsPerColumn': 32,
                                 'columnCount': 2048,
                                 'globalDecay': 0.0,
                                 'initialPerm': 0.21,
                                 'inputWidth': 2048,
                                 'maxAge': 0,
                                 'maxSegmentsPerCell': 128,
                                 'maxSynapsesPerSegment': 32,
                                 'minThreshold': 10,
                                 'newSynapseCount': 20,
                                 'outputType': 'normal',
                                 'pamLength': 1,
                                 'permanenceDec': 0.1,
                                 'permanenceInc': 0.1,
                                 'seed': 1960,
                                 'temporalImp': 'cpp',
                                 'verbosity': 0},
                   'trainSPNetOnlyIfRequested': False},
  'predictAheadTime': None,
  'version': 1}
